// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZ9JlmHY8ID3QyLz3FV_zGjVIpOKY1z0',
    appId: '1:1034419010674:web:4de01eb519dcc84495d6eb',
    messagingSenderId: '1034419010674',
    projectId: 'tweet-mobile-app',
    authDomain: 'tweet-mobile-app.firebaseapp.com',
    storageBucket: 'tweet-mobile-app.appspot.com',
    measurementId: 'G-8VCJPKGCBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKYWDkGx0Y9a3hR7OeK_tWz3pX_0Vjl6U',
    appId: '1:1034419010674:android:5bb2c1470e3ca5d395d6eb',
    messagingSenderId: '1034419010674',
    projectId: 'tweet-mobile-app',
    storageBucket: 'tweet-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLxa5cBfxvmMH5a8QIMU_7FOkGejpr2c',
    appId: '1:1034419010674:ios:b297a750dc8034e395d6eb',
    messagingSenderId: '1034419010674',
    projectId: 'tweet-mobile-app',
    storageBucket: 'tweet-mobile-app.appspot.com',
    androidClientId: '1034419010674-bvs3gcola5sb1pgm01u6vjf376kvi7gq.apps.googleusercontent.com',
    iosClientId: '1034419010674-q07vc4dbqk3cfimme04mf0gbni40eig4.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
